title: "Anna Mariah McAuliffe"
url: "https://hellafolk.github.io"  
baseurl: "/hellafolk"                     
remote_theme: andrewhwanpark/brutalist-blog

avatar: "/hellafolk/img/mask.jpg"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
