
title: "Anna Mariah McAuliffe"
description: "Earth data + instruments + canyon winds."
logo: img/FullSizeRender.jpeg
remote_theme: andrewhwanpark/brutalist-blog

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
